### PR TITLE
Check if the element actually exist

### LINKED ISSUE #538: Enabling Dark Reader kills the example output
**Summary**
Opening a page with example shows broken output when Dark Reader is enabled.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Enable [Dark Reader](https://darkreader.org/) extension
2. Open https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color
3. See the example output exists

**Actual behavior**

image

**Expected behavior**
Output should appear

**Additional context**
Tossed from https://github.com/darkreader/darkreader/issues/3918. I'm afraid that the MDN team also will just toss this issue back to them. Please do some co-work to solve this issue 🙏 (cc @gusted)

### PR DESCRIPTION
**Pull request by Gusted**
- Adds an extra condition to check if the element exist and isn't `null` or `undefined`.
- Resolves #538

### CODE REVIEW

File: editor/js/editor.js [hunk 1]
```diff
@@ -77,7 +77,7 @@
                 var styleElements = shadow.querySelectorAll('style');
 
                 for (var styleElement in styleElements) {
-                    if (styleElements.hasOwnProperty(styleElement)) {
+                    if (styleElements.hasOwnProperty(styleElement) && styleElements[styleElement]) {
```
Comment (saschanaz) [inline editor/js/editor.js:80]: I think the real error is from line 76 😕

Comment (Gusted) [reply editor/js/editor.js:80]: #542 Thanks for the head-ups I missed that one.
