### PR TITLE
Prevents error created by clicking in between example choices

### LINKED ISSUE #586: Clicking in between example choices confuses findParentChoiceElem in mce-utils.js
Related to [#1633](https://github.com/mdn/interactive-examples/issues/1633) within `mdn/interactive-examples`. 

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

Screen Shot 2021-06-27 at 2 36 47 AM

Specifically, L17 is what is failing first, since there isn't a parent element known/defined. I did a few console.log()'s and the `<pre>` gets selected then the `<div class="example-choice">` and finally the DOMTokenList from `parent.classList` like expected when clicking on a example choice.

https://github.com/mdn/bob/blob/1fcea47eb557abd943c3cfdaa0edafa2072ee408/editor/js/editor-libs/mce-utils.js#L9-L20

When we click in between example choices, there isn't a well defined `element.parentElement`. This ultimately stems from the callback in `exampleChoiceList` click event listener. The `findParentElement` method is invoked on the element like `element.findParentElement(target)` in `events.js`. When clicking in between a choice, the `target` becomes the `<section class="example-choice-list">`. I need to take a deeper look to see exactly how/where things are failing.

https://github.com/mdn/bob/blob/1fcea47eb557abd943c3cfdaa0edafa2072ee408/editor/js/editor-libs/events.js#L25-L32

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #586

### CODE REVIEW

File: editor/js/editor-libs/events.js [hunk 1]
```diff
@@ -24,6 +24,14 @@ function addCSSEditorEventListeners(exampleChoiceList) {
...
+
+        // if original target is in between or outside of `example-choice` 
+        // elements, ie the parent <section id='example-choice-list'> element
+        // then bail
+        if (isClickedBetween) {
+            return;
+        }
 
         // if the original target is not an `example-choice` element
         if (!target.classList.contains('example-choice')) {
```
Comment (schalkneethling) [inline editor/js/editor-libs/events.js:37]: @tannerdolby What I find curious is how we even get into this conditional if the `target` does not contains a class with the name `example-choice`

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:37]: I found that a bit curious as well. It works, but is confusing at first glance. Its essentially saying if a user clicks inside the `<code>` element in example choices and not within the parent `<div class="example-choice">` container then find the nearest parent div with `findParentChoiceElem`. I will include a demo below with some console logs to highlight this.

**Comment by tannerdolby** [comment]
Having your eyes on this would be appreciated @peterbe !

File: editor/js/editor-libs/events.js (hunk 1 above)
Comment (schalkneethling) [reply editor/js/editor-libs/events.js:37]: @tannerdolby What if we do this. We add the following function:

```
function handleChoiceEvent() {
    if (this.classList.contains('copy')) {
        mceAnalytics.trackEvent({
            category: 'Interactive Example - CSS',
            action: 'Copy to clipboard clicked',
            label: 'Interaction Events',
        });
    }

    // and pass it on to `onChoose`
    module.exports.onChoose(this);
}
```

and then we replace this block of code with:

```
const exmapleChoices = exampleChoiceList.querySelectorAll(
        '.example-choice'
    );
    Array.from(exmapleChoices).forEach((choice) => {
        choice.addEventListener('click', handleChoiceEvent);
    });
```

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:37]: Instead of `Array.from(exampleChoices)` could we just convert the static NodeList to an array with brackets and the spread operator like `[...exampleChoiceList.querySelectorAll('.example-choice')]`? Either way is fine just wanted to see what your thoughts were.

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:37]: And it wasn't entirely clear, when you say replace 'X' with 'Y', are you referring to replacing 

```js
 var isClickedBetween = target.getAttribute('id') === 'example-choice-list';

        // if original target is in between or outside of `example-choice` 
        // elements, ie the parent <section id='example-choice-list'> element
        // then bail
        if (isClickedBetween) {
            return;
        }
```

with 

```js
const exampleChoiceList = [...document.querySelectorAll('.example-choice')];
        exampleChoiceList.forEach((choice) => {
            choice.addEventListener("click", handleChoiceEvent);
        });
```

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:37]: Since the spread operator will expand the array literal `...stuff` and then using `[]` we create a new array by placing the "spread" values inside brackets like `[...stuff]` this will create a **full** copy on every element. Because `Array.from(arg)` creates a new array from its argument as a "shallow" copy, I reckon your original choice of using `Array.from()` will be best. Sorry for the rant!

File: editor/js/editor-libs/events.js [hunk 2]
```diff
@@ -24,23 +24,19 @@ function addCSSEditorEventListeners(exampleChoiceList) {
...
-            target = mceUtils.findParentChoiceElem(target);
-        }
-
-        if (target.classList.contains('copy')) {
-            mceAnalytics.trackEvent({
-                category: 'Interactive Example - CSS',
-                action: 'Copy to clipboard clicked',
-                label: 'Interaction Events'
-            });
+        var isClickedBetween = target.getAttribute('id') === 'example-choice-list';
```
Comment (schalkneethling) [inline editor/js/editor-libs/events.js:27]: @tannerdolby I don’t think we need this anymore. We are only attaching events to the actual `example-choice` elements. We are no longer listening on the parent `example-choice-list`. Agree?

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:27]: Agreed, we don't need that stuff anymore as were only listening on the `.example-choice`'s themselves and not using `mce.findParentElem(event.target)` which made it necessary to return if `event.target` was the parent `example-choice-list`.

Comment (schalkneethling) [reply editor/js/editor-libs/events.js:27]: Doh! I completely missed that it is still inside that event handler. We do not actually need that either anymore.

Comment (tannerdolby) [reply editor/js/editor-libs/events.js:27]: A way to fix this, would be to simply place our `Array.from()` code outside of the `exampleChoiceList.addEventListener("click"..)` block so that the click event listeners get added to each choice right away instead of adding new event listeners every time the parent `example-choice-list` is clicked. This way, we only need to click each `example-choice` once as the click event is already attached and the callback `handleChoiceEvent` fires as expected.

Replace
```js
exampleChoiceList.addEventListener("click", () => {
  ... 
   Array.from().forEach((choice), => {
      choice.addEventListener("click", handleChoiceEvent)
   })
})
```

with 

```js
var exampleChoices = exampleChoiceList.querySelectorAll('.example-choice');
Array.from().forEach((choice), => {
      choice.addEventListener("click", handleChoiceEvent)
   })
```

Comment (tannerdolby) [reply editor/js/editor-libs/events.js]: I fixed things up here, the click between choices still works as expected and doesn't produce any errors (or anything) for that matter as there isn't any click event attached to the parent `example-choice-list`. And now our logic is outside of the parent click event so things are firing as expected.

Comment (tannerdolby) [reply editor/js/editor-libs/events.js]: I see that `var mceUtils = require('./mce-utils');` is unused in the imports so we could probably remove that as we aren't using any methods from `mceUtils` anymore.

Comment (schalkneethling) [reply editor/js/editor-libs/events.js]: We can clean that up as well. Thanks, @tannerdolby

Comment (tannerdolby) [reply editor/js/editor-libs/events.js]: Got it. Your welcome @schalkneethling !

**Comment by tannerdolby** [comment]
Should be good to go now 🎉  @schalkneethling

**Review by schalkneethling — APPROVED** [review]
Thank you, @tannerdolby 🎉
